[package]
name = "cosmogony"
version = "0.3.0"
authors = ["Adrien Matissart <a.matissart@qwantresearch.com>", "Antoine Desbordes <antoine.desbordes@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/osm-without-borders/cosmogony"
homepage = "http://cosmogony.world"
keywords = ["osm", "boundary", "geography"]
categories = ["science", "algorithms"]
description = "Provides geographical zones with a structured hierarchy"
readme = "README.md"


[badges]
travis-ci = { repository = "osm-without-borders/cosmogony" }

[dependencies]
log = "0.4"
env_logger = "0.5"
geo = "0.6"
structopt = "0.1"
structopt-derive = "0.1"
osmpbfreader = "^0.11"
serde = {version = "1", features = ["rc"]}
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.7"
itertools = "0.7"
geojson = "0.9"
failure = "0.1"
failure_derive = "0.1"
gst = "0.1.3"
ordered-float = "0.0.2"
osm_boundaries_utils = "0.2"
geos = "~1.0"
regex = "0.2"
lazy_static = "1.0.0"
flate2 = "1.0"
